# Generated by Django 4.2.16 on 2026-09-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_game_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('game_code', models.CharField(blank=True, max_length=6)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='game_event_event_t_a42673_idx'), models.Index(fields=['session_id'], name='game_event_session_55cf94_idx')],
            },
        ),
    ]
